name: cocktail_recipe_manager
description: "Cocktail Book - A cocktail recipe manager app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.4
  path: ^1.9.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.3.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.20.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/presets/preset_recipes.json
